version: '3.6'

services:
  # api:
  #   build: api_backend
  #   depends_on:
  #     - db
  #   environment:
  #     STAGE: test
  #     SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
  #   networks:
  #     - default
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./api_backend:/usr/src/api
  #     - ./api_backend/migrations:/usr/src/app/migrations
  #   restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./data-postgres:/var/lib/postgresql
      - ./sql/1_setup.sql:/docker-entrypoint-initdb.d/1_setup.sql
      - ./sql/2_create_tables.sql:/docker-entrypoint-initdb.d/2_create_tables.sql